services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: leanadmin
      POSTGRES_PASSWORD: leanpass26
      POSTGRES_DB: lean_dev
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
